export const aiMessages = {
  'en-US': {
    title: 'AI assistant', description: 'Review redacted logs. Approve commands. Stay in control.',
    config: 'AI API settings', base: 'API base URL (include /v1 if required)', model: 'Model ID', key: 'API Key', keySaved: 'Key stored encrypted; leave blank to keep it', save: 'Save', test: 'Test connection', remove: 'Delete configuration', removeConfirm: 'Delete your AI API configuration?', saved: 'Saved', tested: 'Connection successful',
    policy: 'Compatible Chat Completions API over public HTTPS (port 443) only. No private-network endpoints or redirects. Keys are encrypted on the backend and never returned to the browser.',
    task: 'What should AI help with?', logs: 'Selected terminal text / logs', contextHint: 'Only this text and your task are sent. No automatic terminal history collection. Maximum 64,000 characters.', targets: 'SSH targets', targetHint: 'Select none for analysis only. Commands will run on every selected target in new SSH execution channels, not in your current interactive shell.', search: 'Search servers', empty: 'No SSH servers found', preview: 'Preview redacted content', previewTitle: '1 · Review outgoing content',
    warning: 'Masking is best effort, not a guarantee. Review for business secrets and personal data. Your API provider receives the displayed content and model ID, plus fixed safety/response-format instructions. Its own data policies apply.', sendConsent: 'I have reviewed the content and approve sending it to this provider.', send: 'Send to AI', result: '2 · Analysis and proposed commands', executeWarning: 'AI can make mistakes, including destructive commands. Review every command. The server account’s privileges apply. No automatic retries or unapproved follow-up commands.', executeConsent: 'I approve these exact commands on the targets listed below.', execute: 'Execute approved commands', password: 'Temporary password / key passphrase (SSH only; never sent to AI)', requiredPassword: 'Enter the temporary password for', job: '3 · Execution result', refresh: 'Refresh', stop: 'Request cancellation', follow: 'Use result for another analysis', audit: 'Recent AI activity', working: 'Working…', failed: 'Operation failed. Please check the configuration or connection.', noCommands: 'No executable command proposal. You can refine your task and preview again.', selection: 'AI · analyze selection', changeHint: 'Editing inputs invalidates previous previews and command approvals.', cancelled: 'Cancellation requested. Remote effects already applied cannot be undone.', restoreJob: 'View job',
  },
  'zh-CN': {
    title: 'AI 助手', description: '先检查脱敏日志，再确认命令，操作始终由你掌控。',
    config: 'AI API 设置', base: 'API 基础地址（按服务商要求包含 /v1）', model: '模型 ID', key: 'API Key', keySaved: '密钥已加密保存，留空保留原密钥', save: '保存', test: '测试连接', remove: '删除配置', removeConfirm: '删除你的 AI API 配置？', saved: '已保存', tested: '连接测试成功',
    policy: '支持兼容 Chat Completions 的公网 HTTPS API（443 端口）。不允许内网地址或重定向。密钥在后端加密保存，不会回传浏览器。',
    task: '你希望 AI 帮你处理什么？', logs: '选中的终端文本 / 日志', contextHint: '只发送此处文本和任务，不自动采集终端历史。最多 64,000 字。', targets: 'SSH 目标服务器', targetHint: '不选择服务器则仅分析。命令会在每台所选服务器的新 SSH 执行通道运行，不继承当前交互终端的目录或环境。', search: '搜索服务器', empty: '没有 SSH 服务器', preview: '预览脱敏内容', previewTitle: '1 · 检查即将发送的内容',
    warning: '自动脱敏不是绝对保证，请检查业务秘密和个人信息。服务商将收到下方内容、模型 ID 以及固定的安全和输出格式指令，数据处理遵循该服务商的政策。', sendConsent: '我已检查内容，同意发送给此 API 服务商。', send: '发送给 AI', result: '2 · 分析及建议命令', executeWarning: 'AI 可能给出错误甚至破坏性命令，请逐条检查。执行权限等同服务器账号权限。不自动重试，不自动执行后续命令。', executeConsent: '我确认在下方列出的目标服务器执行这些确切命令。', execute: '执行已确认命令', password: '本次密码 / 私钥口令（仅供 SSH 使用，绝不发送给 AI）', requiredPassword: '请填写本次密码：', job: '3 · 执行结果', refresh: '刷新', stop: '请求停止', follow: '用结果继续分析', audit: '最近 AI 操作记录', working: '处理中…', failed: '操作失败，请检查配置或连接。', noCommands: '没有可执行的命令建议。可以修改任务后重新预览。', selection: 'AI · 分析选中文本', changeHint: '修改输入会使此前的预览和命令确认失效。', cancelled: '已请求停止，远端已经产生的修改不会自动撤销。', restoreJob: '查看任务',
  },
  'ja-JP': {
    title: 'AI アシスタント', description: 'マスク済みログを確認し、コマンドを承認して実行します。',
    config: 'AI API 設定', base: 'API ベース URL（必要に応じて /v1 を含む）', model: 'モデル ID', key: 'API Key', keySaved: 'キーは暗号化済み。空欄で保持', save: '保存', test: '接続テスト', remove: '設定を削除', removeConfirm: 'AI API 設定を削除しますか？', saved: '保存しました', tested: '接続に成功しました',
    policy: '公開 HTTPS（443）の Chat Completions 互換 API に対応。内部アドレスとリダイレクトは禁止。キーはバックエンドで暗号化され、ブラウザーに返されません。',
    task: 'AI に依頼する内容', logs: '選択した端末テキスト / ログ', contextHint: 'このテキストと依頼のみを送信。端末履歴は自動収集しません。最大 64,000 文字。', targets: 'SSH 対象サーバー', targetHint: '未選択なら分析のみ。各対象の新しい SSH 実行チャネルで実行され、対話端末の環境は引き継ぎません。', search: 'サーバーを検索', empty: 'SSH サーバーがありません', preview: 'マスク済み内容を確認', previewTitle: '1 · 送信内容の確認',
    warning: '自動マスクは完全ではありません。機密情報と個人情報をご確認ください。表示内容、モデル ID、固定の安全・出力形式指示がプロバイダーに送信され、そのデータポリシーが適用されます。', sendConsent: '内容を確認し、このプロバイダーへの送信を承認します。', send: 'AI に送信', result: '2 · 分析と提案コマンド', executeWarning: 'AI は破壊的なコマンドを含む誤りを起こす場合があります。全コマンドを確認してください。サーバーアカウントの権限で実行。自動再試行や未承認の追加実行はありません。', executeConsent: '以下の対象で、表示されたコマンドの実行を承認します。', execute: '承認済みコマンドを実行', password: '一時パスワード / キーパスフレーズ（SSH 専用、AI には送信しません）', requiredPassword: '一時パスワードを入力：', job: '3 · 実行結果', refresh: '更新', stop: '停止を要求', follow: '結果を再分析に使用', audit: '最近の AI 操作', working: '処理中…', failed: '操作に失敗しました。設定や接続を確認してください。', noCommands: '実行可能な提案がありません。依頼を修正して再確認できます。', selection: 'AI · 選択内容を分析', changeHint: '入力を変更すると、前のプレビューと承認が無効になります。', cancelled: '停止を要求しました。実行済みの変更は元に戻りません。', restoreJob: 'タスクを表示',
  },
};
