const en = {
  monitoring: 'Monitoring', resize: 'Resize agent panel', description: 'Public Nezha telemetry and explicit SSH device bindings.',
  url: 'Public Nezha dashboard URL', hint: 'Uses the public live status API, without credentials. Refreshes every 5 seconds while visible. Changing the URL clears node bindings.',
  node: 'Monitor node', device: 'FleetDeck device', unbound: 'Not bound', load: 'Load (1 / 5 / 15 min)', network: 'Network in / out', memory: 'Memory', disk: 'Disk', stale: 'Data unavailable or stale; do not use it as current server state.',
  aliases: 'Device aliases', aliasHint: 'Separate aliases with commas, e.g. server one, database. Aliases must be unique; ambiguous names require manual selection.',
  includeMonitor: 'Include fresh monitoring snapshot', includeInventory: 'Include device names and aliases', resolve: 'Find devices mentioned in message', useMatches: 'Use these devices as scope', ambiguous: 'Ambiguous name: select the intended devices manually.',
  selection: 'Attach terminal selection', recent: 'Attach last 120 terminal lines', noTerminal: 'No readable active SSH terminal.', switchScope: 'Replace the current context and execution scope with this terminal device?',
  persisted: 'Conversation stays in memory while navigating. Saving is optional and encrypted after redaction.', saveChat: 'Save encrypted conversation', savedChats: 'Saved conversations', loadChat: 'Load as history', deleteChat: 'Delete conversation', deleteConfirm: 'Permanently delete this saved conversation?',
  reviewResult: 'Analyze the execution result and suggest the next step. Do not assume commands succeeded.', askMonitor: 'Analyze monitored server health and identify stale or overloaded nodes.',
  lastUpdate: 'Snapshot time', offline: 'Stale / offline', online: 'Recent report', analyze: 'Discuss with agent', empty: 'No monitoring data yet. Save the URL to connect.', source: 'Context source',
};
export const opsMessages = {
 'en-US': en,
 'zh-CN': { ...en, monitoring: '监控探针', resize: '调整 Agent 面板宽度', description: '哪吒公开实时状态与 SSH 设备的显式关联。', url: '哪吒公开面板地址', hint: '通过公开实时接口读取，无需账号密钥。页面可见时每 5 秒刷新。更换地址会清除节点绑定。', node: '监控节点', device: 'FleetDeck 设备', unbound: '未绑定', load: '负载（1 / 5 / 15 分钟）', network: '网络入站 / 出站', memory: '内存', disk: '磁盘', stale: '数据不可用或已过期，请勿据此判断服务器当前状态。', aliases: '设备别名', aliasHint: '多个别名用逗号分隔，例如：1号服务器, 数据库。别名不能重复；名称有歧义时需手动选择。', includeMonitor: '附加最新监控快照', includeInventory: '附加设备名称和别名清单', resolve: '识别消息中提到的设备', useMatches: '将这些设备设为执行范围', ambiguous: '名称存在歧义，请手动勾选正确的设备。', selection: '附加终端选区', recent: '附加终端最近 120 行', noTerminal: '没有可读取的活动 SSH 终端。', switchScope: '用此终端设备替换当前日志及执行范围？', persisted: '切换页面保留内存对话；可选保存，脱敏后加密存储。', saveChat: '加密保存对话', savedChats: '已保存对话', loadChat: '载入为历史', deleteChat: '删除对话', deleteConfirm: '永久删除这条已保存对话？', reviewResult: '请分析执行结果并提出下一步建议，不要假定命令已成功。', askMonitor: '分析监控中的服务器健康状态，指出过期数据和高负载节点。', lastUpdate: '快照时间', offline: '过期 / 离线', online: '近期上报', analyze: '与 Agent 讨论', empty: '暂无监控数据，保存地址后开始读取。', source: '上下文来源' },
 'ja-JP': { ...en, monitoring: '監視', resize: 'Agent 幅を変更', description: 'Nezha の公開状態と SSH デバイスの関連付け。', url: 'Nezha 公開 URL', hint: '認証なしで公開 API を読み取ります。表示中は 5 秒ごとに更新。URL 変更で関連付けを解除します。', node: '監視ノード', device: 'FleetDeck デバイス', unbound: '未関連付け', load: '負荷（1 / 5 / 15 分）', network: '受信 / 送信', memory: 'メモリ', disk: 'ディスク', stale: 'データが取得不可または古くなっています。', aliases: '別名', aliasHint: '別名はカンマ区切りで一意に指定。曖昧な名前は手動で選択してください。', includeMonitor: '最新の監視スナップショットを添付', includeInventory: 'デバイス名と別名を添付', resolve: 'メッセージ内のデバイスを検索', useMatches: 'このデバイスを対象にする', ambiguous: '曖昧な名前です。対象を手動で選択してください。', selection: '端末の選択範囲を添付', recent: '端末の直近 120 行を添付', noTerminal: '読み取り可能な SSH 端末がありません。', switchScope: '現在のログと対象をこの端末に置き換えますか？', persisted: '画面移動後も会話を保持。任意でマスク後に暗号化保存できます。', saveChat: '会話を暗号化保存', savedChats: '保存済み会話', loadChat: '履歴として読み込む', deleteChat: '会話を削除', deleteConfirm: '保存済み会話を完全に削除しますか？', reviewResult: '実行結果を分析して次の手順を提案してください。成功を仮定しないでください。', askMonitor: '監視データから古い情報と高負荷ノードを特定してください。', lastUpdate: '取得時刻', offline: '古い / オフライン', online: '最近の報告', analyze: 'Agent と相談', empty: 'URL を保存して監視を開始してください。', source: '情報源' },
};
